### ISSUE TITLE
stat_3d.pth.tar missing

### ISSUE THREAD

**Issue by victoriamazo** [weigq/3d_pose_baseline_pytorch#12]
Hi! When I try to run test I get error:
FileNotFoundError: [Errno 2] No such file or directory: 'data/stat_3d.pth.tar'

**Comment by monajalal** [comment]
@victoriamazo could you please share the link to this dataset?

**Comment by yashkhem1** [comment]
@victoriamazo Yeah, please share the link to this dataset, that would be great
