### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by NguyenDangBinh** [weigq/3d_pose_baseline_pytorch#14]
dear @weigq,
What is that?
# optional arguments, you can access more details in opt.py
main.py [-h] [--data_dir DATA_DIR] [--exp EXP] [--ckpt CKPT]
           [--load LOAD] [--test] [--resume]
           [--action {all,All}]
           [--max_norm] [--linear_size LINEAR_SIZE]
           [--num_stage NUM_STAGE] [--use_hg] [--lr LR]
           [--lr_decay LR_DECAY] [--lr_gamma LR_GAMMA] [--epochs EPOCHS]
           [--dropout DROPOUT] [--train_batch TRAIN_BATCH]
           [--test_batch TEST_BATCH] [--job JOB] [--no_max] [--max]
           [--procrustes]

**Comment by weigq** [comment]
what ?

**Comment by NguyenDangBinh** [comment]
dear @weigq,
How to adjust it?

**Comment by NguyenDangBinh** [comment]
dear @weigq,
how to do that?
