### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by zc-alexfan** [weigq/3d_pose_baseline_pytorch#17]
Thanks for the great repo! Your code is very elegant. Just a quick question. I am trying to plot the given 2d and 3d processed skeletons. However, I could not find the connection between joints in your repo. I am wondering if you could either provide the limb connections or the code for visualizing? 

Thanks a lot!

**Comment by weigq** [comment]
You can refer to [here](https://github.com/una-dinosauria/3d-pose-baseline/blob/826df8cb1541afd1bb0b80ad6d6ad55ef8b313de/src/data_utils.py#L20).

**Comment by zc-alexfan** [comment]
Thanks for the quick reply! I did checkout this repo. But it seems that it has 17 joints while your repo's data is 16 joints?

**Comment by weigq** [comment]
the pose is aligned with hip joint, so the center hip is (0, 0, 0) as default.
