### ISSUE TITLE
Error computation

### ISSUE THREAD

**Issue by macaodha** [weigq/3d_pose_baseline_pytorch#2]
Hi there, 

Thanks again for sharing your code, its very clear. 

I have a quick question about the error computation. You select the valid dimensions [here](https://github.com/weigq/3d_pose_baseline_pytorch/blob/master/main.py#L230) which includes dimensions for the hip (which is not predicted) for. As I understand it, in the squared error [computation](https://github.com/weigq/3d_pose_baseline_pytorch/blob/master/main.py#L243) three of the dimensions will always have a very low error e.g. they are predicted zero and the gt is zeros. 

Is this the same way as the original TensorFlow code? 

Thanks

**Comment by weigq** [comment]
Yeap, it is same as the original code,
the network actually predicts 16 joints not including the hip, which means that the hip joint is aligned to GT hip joint. So, in fact , the number of joints predicted is 17, as same to most 3d pose estimation methods.

**Comment by macaodha** [comment]
Perfect, thanks for clarifying.
