### ISSUE TITLE
Data Missing

### ISSUE THREAD

**Issue by yashkhem1** [weigq/3d_pose_baseline_pytorch#25]
Hi,
I can't find the h36m.zip in the drive link. Could you please upload it again and share the new link?
Thanks

**Comment by MCLYang** [comment]
https://github.com/facebookresearch/VideoPose3D/blob/master/DATASETS.md

**Comment by kevinlemon** [comment]
@malcolmyanguci This dataset is not in the right form. Your link provides  '.h5' files while the code needs '.pth.tar' files

**Comment by ericzw** [comment]
> @malcolmyanguci This dataset is not in the right form. Your link provides '.h5' files while the code needs '.pth.tar' files

hi, have you obtained the human3.6 dataset?

**Comment by yashkhem1** [comment]
Hi, so I seem to have resolved this issue. All I needed to do was to run the data-processing code for the TensorFlow repository and then save the resultant poses in .pth.tar files. For the 3d posed, the data_mean, data_std and dimenions_to_use that are returned by the function are to be stored in stat_3d.pth.tar
The link to the above files is https://drive.google.com/drive/folders/1h4S3vmtjso_rxP6_Lfg6a1ue7pJMuGp9
Since the link is temporary, can someone reupload it and then share the link.

**Comment by kevinlemon** [comment]
@yashkhem1 
I am sorry to bother you. There are numerous functions in data-processing code (https://github.com/una-dinosauria/3d-pose-baseline/blob/master/src/data_utils.py). Could you tell me the relationship between functions and stored files?
Thanks

**Comment by yashkhem1** [comment]
@kevinlemon 
I used these 3 functions for processing the data:-
1) read_3d_data :- train_set and test_set are saved as train_3d.pth.tar and test_3d.pth.tar respectively. data_mean, data_std, dim_to_use are stored in a dictionary named stat_3d with key values being mean, std and dim_use respectively. This dictionary is saved as stat_3d.pth.tar.
2) create_2d_data:- train_set and test_set are saved as train_2d.pth.tar and test_2d.pth.tar respectively
3) read_2d_predictions:- train_set and test_set are saved as train_2d_ft.pth.tar and test_2d_ft.pth.tar respectively.

Hope this answers your questions.

**Comment by kevinlemon** [comment]
@yashkhem1 
Great! Thanks a lot

**Comment by mozpp** [comment]
> @kevinlemon
> I used these 3 functions for processing the data:-
> 
>     1. read_3d_data :- train_set and test_set are saved as train_3d.pth.tar and test_3d.pth.tar respectively. data_mean, data_std, dim_to_use are stored in a dictionary named stat_3d with key values being mean, std and dim_use respectively. This dictionary is saved as stat_3d.pth.tar.
> 
>     2. create_2d_data:- train_set and test_set are saved as train_2d.pth.tar and test_2d.pth.tar respectively
> 
>     3. read_2d_predictions:- train_set and test_set are saved as train_2d_ft.pth.tar and test_2d_ft.pth.tar respectively.
> 
> 
> Hope this answers your questions.

how to  save a dict to pth.tar?

**Comment by alecda573** [comment]
@yashkhem1 @MCLYang how exactly are we suppose to get the data out of the .pth.tar files. Whenever I try to extract the files I get corrupted/damaged error and no archive found... any help would be appreciated!
