### ISSUE TITLE
Stacked Hourglass Detections

### ISSUE THREAD

**Issue by mkocabas** [weigq/3d_pose_baseline_pytorch#3]
Hi @weigq,

Thanks for the great implementation. I'm trying to train on SHG detections but the .zip file doesn't contain the `test_2d_ft.pth.tar` file. 

Could you provide detection files or processing script for that?

**Comment by weigq** [comment]
I used the fine-tuned 2d poses from the original [implementation](https://github.com/una-dinosauria/3d-pose-baseline). 

I will upload it asap

**Comment by mkocabas** [comment]
Thanks for quick answer. I look forward to it!

**Comment by mkocabas** [comment]
Hi @weigq, any update on this? Did you have a chance to upload it?

**Comment by mkocabas** [comment]
@weigq, any update?

**Comment by weigq** [comment]
@mkocabas 
Sorry, I will update by the end of this month.

**Comment by mkocabas** [comment]
Thanks @weigq, but I don't need them anymore. I've adapted the original dataloaders to pytorch.

**Comment by vasusingla** [comment]
I can't reproduce results from stacked hourglass predictions for 3D pose baseline. Can anyone provide the results they obtained or the code for the stacked hourglass predictions?

@mkocabas @weigq

**Comment by benjiebob** [comment]
Thanks so much for uploading your code. Just a quick clarification... are the stacked hourglass detections in the zip file the 'finetuned' versions from here https://drive.google.com/file/d/0BxWzojlLp259S2FuUXJ6aUNxZkE/view

**Comment by benjiebob** [comment]
Wondering if there might be any update on this issue before I write the code to convert the predictions from https://drive.google.com/file/d/0BxWzojlLp259S2FuUXJ6aUNxZkE/view

**Comment by mkocabas** [comment]
Dear @vasusingla619, @benjiebob,

I modified the [original tf preprocessing](https://github.com/una-dinosauria/3d-pose-baseline/blob/master/src/predict_3dpose.py#L153) to pytorch instead of depending preprocessed `*.tar`s provided by @weigq. I would share it if you need.

**Comment by zhangyahu1** [comment]
Dear @mkocabas,

Could you please share your modified version? Thanks!
