### ISSUE TITLE
Problem on Visualizing

### ISSUE THREAD

**Issue by ghost** [weigq/3d_pose_baseline_pytorch#33]
I follow with https://github.com/weigq/3d_pose_baseline_pytorch/blob/a03094bb479770abc43dc5b87ad394b85bb6dcab/main.py#L226 to unnorm the output of network, and get tensor which has  (51, ) shape.  I guess it should be the coordinates like x0,y0,z0,x1,y1,z1.......x16,y16,z16
but when I draw all 17 point in 3d plot, it don't like a human skeleton shape, 

I want to know how to visualize the output from the (51, ) array, and the index of these 51 nums.

**Comment by weigq** [comment]
Did you visualize the pose after unnormalization?

**Comment by ghost** [comment]
> Did you visualize the pose after unnormalization?

No, I want to visualize the 3d pose by the (51, ) shape tensor that I got, but it seems not work.

**Comment by weigq** [comment]
The normalized pose is normalized for each joint separately (i.e., each type of joint has a mean and std), therefore the normalized pose dose not look like a person. If you want to visualize the pose, you need to unnormalize it first.

**Comment by ghost** [comment]
> The normalized pose is normalized for each joint separately (i.e., each type of joint has a mean and std), therefore the normalized pose dose not look like a person. If you want to visualize the pose, you need to unnormalize it first.

Yes, I have done the unnormalize work first, follow with https://github.com/weigq/3d_pose_baseline_pytorch/blob/a03094bb479770abc43dc5b87ad394b85bb6dcab/main.py#L226
and get the parameter which named outputs_unnorm and outputs_use in your code, I think it should be the unnormalized result, and how can I handle this parameter to get the visualizing pose?

**Comment by weigq** [comment]
You can refer to https://github.com/una-dinosauria/3d-pose-baseline/blob/666080d86a96666d499300719053cc8af7ef51c8/src/data_utils.py#L17 for the orders of joints

**Comment by ghost** [comment]
> You can refer to https://github.com/una-dinosauria/3d-pose-baseline/blob/666080d86a96666d499300719053cc8af7ef51c8/src/data_utils.py#L17 for the orders of joints

This is where I have problem, does your order same as his? 
For example, for (51, ) shape tensor, first three nums represent the coordinates of Hip, the 4,5,6-th nums represent the coordinates of RHip, the last three nums represent the coordinates of RWrist?
Because I have try in this order but got strange result.

I notice that you are from Beijing, can I add your Wechat to talk about it In detail？

**Comment by weigq** [comment]
You can send your wechat to my email

**Comment by ghost** [comment]
> You can send your wechat to my email

Hi, I have send my WeChat to your @gmail email, please take a look, hope for communicating with you

**Comment by alexivaner** [comment]
Hi, how you visualize the join? I already have (51,) unnormalized 3d skeleton, how I could visualize it? Thank you. 
Because I always get this error:

`AssertionError: channels should have 96 entries, it has 51 instead
`
![image](https://user-images.githubusercontent.com/57290644/105796814-a0c17e80-5fca-11eb-9303-b90d8c8b3bae.png)

I am sorry if this is a silly question, how we could get 96 entries if we only have 51 coordinates of join? Is there a way to make it have 96 entries. Thanks
