### ISSUE TITLE
Unnormalize and Normalize 2D Skeleton

### ISSUE THREAD

**Issue by alexivaner** [weigq/3d_pose_baseline_pytorch#35]
Hi, since the dataset provided here is normalized version, could anyone give me idea how to unnormalize 2D Skeleton? I already see this function and successfully unnormalize the 3D Skeleton, but how we use this code to unnormalize 2D Skeleton? I will really glad if someone could help. Also is there a function to do normalize? Thank you. 

`def unNormalizeData(normalized_data, data_mean, data_std, dimensions_to_use):`

**Comment by bsridatta** [comment]
Just multiply std and add mean. And you don't have those numbers. If you have access to original data and tuned model, you can easily get all these. I guess its time to move to new dataset like CMU Panoptic as there is no response to request for H3.6M data

**Comment by lee-man** [comment]
@alexivaner 
I am facing the same problem, and I have no access to the original data. Could you share the 2d statistics? Thanks!

**Comment by alexivaner** [comment]
@lee-man Hi, due to dataset license issue, I could not share directly. I already get Human3.6M dataset license, if you already get it too, I could share it with you.

**Comment by lee-man** [comment]
@alexivaner Thanks for your quick reply. I just asked my supervisor and he said that our team has the license to the dataset. It would be great if you can share the stat with me. Thanks!

**Comment by alexivaner** [comment]
> @alexivaner Thanks for your quick reply. I just asked my supervisor and he said that our team has the license to the dataset. It would be great if you can share the stat with me. Thanks!

Hi, can you give me your email? if it is an education institution email, it will be better.

**Comment by lee-man** [comment]
> > @alexivaner Thanks for your quick reply. I just asked my supervisor and he said that our team has the license to the dataset. It would be great if you can share the stat with me. Thanks!
> 
> Hi, can you give me your email? if it is an education institution email, it will be better.

Sure. My email is mli@cse.cuhk.edu.hk 
Thanks a lot!
