### ISSUE TITLE
Hourglass detection files

### ISSUE THREAD

**Issue by DuncanZauss** [weigq/3d_pose_baseline_pytorch#36]
Hello,

The SH detections do not seem to be available anymore. Also in the main repo (https://github.com/una-dinosauria/3d-pose-baseline) there is no code available for hourglass detections. Does anyone happen to have the detection files, i.e. 'train_2d_ft.pth.tar' and 'test_2d_ft.pth.tar'? Or the code for the stacked hourglass model that was used to produce the results?

At the moment I am only able to run my experiments with the GT. It would be great if someone could help me with the SH detections :)

Cheers,
Duncan

**Comment by Charlulote** [comment]
detection files with SHM [here](https://drive.google.com/drive/folders/1h4S3vmtjso_rxP6_Lfg6a1ue7pJMuGp9), which has been in #25

**Comment by DuncanZauss** [comment]
Nice! Thank you very much!

**Comment by guoyuhang1996** [comment]
@Charlulote  Hello! Have you run train_2d_ft.pth.tar and test_2d_ft.pth.tar on other models and I've run it on other models, whose performance is very poor. So I want to know if the train_2d_ft.pth.tar contains the same kind of joints and the same order of joints as it did on train_2d.pth.tar and train_3d.pth.tar ? Thanks!

**Comment by Charlulote** [comment]
@guoyuhang1996 there are similar issues to yours, where he explains his mistaking in processing the predicted results of hourglass model.  you can check

**Comment by guoyuhang1996** [comment]
Thank you so much for your reply. But can you tell me where did he explain his mistake?

**Comment by guoyuhang1996** [comment]
Thank you so much for your reply. But can you tell me where did he explain his mistake? @Charlulote
