### ISSUE TITLE
why 3d pose is similar

### ISSUE THREAD

**Issue by huidemie** [weigq/3d_pose_baseline_pytorch#37]
hello, I visualize the 3d skeleton and it looks like a human. But why the results of different datasets looks very similar ?

**Comment by weigq** [comment]
Can you provide more details?

**Comment by huidemie** [comment]
For example, when I visualize one of the 3d results in "sitting down" dataset,  it looks like the following picture. I don't think it is "sitting down" action. Besides, 3d result in different datasets looks like the following picture all the same. 
![1618406692(1)](https://user-images.githubusercontent.com/53325307/114719674-e855dc00-9d69-11eb-8b4f-c7267199c8bb.png)

**Comment by weigq** [comment]
You used the H36m dataset or other dataset to visualize?

**Comment by huidemie** [comment]
> You used the H36m dataset or other dataset to visualize?

I use H36M

**Comment by weigq** [comment]
I am not sure which samples you used. Let me guess if you only use the first several frames in each video (like, you only use the first frame of each action)? In h36m, the poses in the first several frames are every similar, where the actor is standing like you ploted.

**Comment by huidemie** [comment]
> I am not sure which samples you used. Let me guess if you only use the first several frames in each video (like, you only use the first frame of each action)? In h36m, the poses in the first several frames are every similar, where the actor is standing like you ploted.

You are right ! Thanks a lot !
