### ISSUE TITLE
Joints Order

### ISSUE THREAD

**Issue by guoyuhang1996** [weigq/3d_pose_baseline_pytorch#38]
@weigq  Hello! I've run train_2d_ft.pth.tar and test_2d_ft.pth.tar on other models, whose performance is very poor. So I want to know if the train_2d_ft.pth.tar contains the same kind of joints and the same order of joints as it did on train_2d.pth.tar and train_3d.pth.tar ? Thanks!

**Comment by weigq** [comment]
Yes
