### ISSUE TITLE
Bug in Error Calculation

### ISSUE THREAD

**Issue by ssfootball04** [weigq/3d_pose_baseline_pytorch#8]
Hi,
Wanted to point out a bug in your error calculation. The errors for all actions are simply averaged, without regard to the number of data points in each action. It should be a weighted mean. This yields slightly higher numbers.

**Comment by weigq** [comment]
@ssfootball04 
Good point, the weights are usually not taken into account when calculating the errors under protocol #1/2, since the results under these protocols are the average error among actions.

**Comment by ssfootball04** [comment]
I don't think that's right, from all the papers I've come across. Can you give a reference ?

**Comment by weigq** [comment]
I saw you have submitted the same issue on the original repo, so I closed now.
